"""add rrule to tasks

Revision ID: 60b5b2c05689
Revises: 4d42925f93a5
Create Date: 2026-04-27 13:27:28.567202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b5b2c05689'
down_revision: Union[str, Sequence[str], None] = '4d42925f93a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('rrule', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tasks', sa.Column('parent_task_id', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'scheduled_for')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'is_recurring')
    op.drop_column('tasks', 'rrule')
    # ### end Alembic commands ###
