"""add priority and quality score to tasks

Revision ID: e81cc694af5c
Revises: dafe9cfe640a
Create Date: 2026-04-27 19:22:37.162372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81cc694af5c'
down_revision: Union[str, Sequence[str], None] = 'dafe9cfe640a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.String(length=20), nullable=False, server_default='normal'))
    op.add_column('tasks', sa.Column('quality_score', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('quality_comment', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('quality_reviewed_by', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('quality_reviewed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['quality_reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'quality_reviewed_at')
    op.drop_column('tasks', 'quality_reviewed_by')
    op.drop_column('tasks', 'quality_comment')
    op.drop_column('tasks', 'quality_score')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
